### ISSUE TITLE
Incorrect unfolding of orphan transitions in CPNs

### ISSUE THREAD

**Issue by MathiasMehl** [TAPAAL/verifypn#100]
The net: 
![image](https://user-images.githubusercontent.com/33687173/170228844-a4224478-6c32-4c9e-a772-763c6185d4c0.png)

Gets unfolded to: 
![image](https://user-images.githubusercontent.com/33687173/170228897-7c98fb92-b213-4a71-8543-1ea3a1a95023.png)

This is fixed if a place is added to T0's preset.

Model and query attached. Command: `-R 0 -x 1 unfold-example.pnml unfold-example-queries.xml --write-unfolded-net unfolded.pnml`

[unfold-example-orphan-transition.zip](https://github.com/TAPAAL/verifypn/files/8769692/unfold-example-orphan-transition.zip)

**Comment by petergjoel** [comment]
Fixed in https://github.com/TAPAAL/verifypn/commit/ba515f7f25104478e6068aa8400e55c7b4df2454
