### ISSUE TITLE
LP approximation gives wrong answer

### ISSUE THREAD

**Issue by srba** [TAPAAL/verifypn#116]
Verify the attached net (in hyper-LTL GUI branch). With query simplificaton it says FALSE (wrong answer) and without it says TRUE (correct answer). Please, check if this is an issue also for verifypn (with CPN gui branch) branch and normal LTL or not.
[hyper-LTL-error-query-simpl.tapn.zip](https://github.com/TAPAAL/verifypn/files/10186447/hyper-LTL-error-query-simpl.tapn.zip)

**Comment by petergjoel** [comment]
Seems fixed in https://github.com/TAPAAL/verifypn/commit/ba515f7f25104478e6068aa8400e55c7b4df2454
