### ISSUE TITLE
Possible bug printing queries of the form EX

### ISSUE THREAD

**Issue by n-vds** [TAPAAL/verifypn#162]
Dear TAPAAL team,

I have noticed a possible bug in the query display implementation: Formulas of the form EX are displayed as "AF" instead.
See https://github.com/TAPAAL/verifypn/blob/be1f6aa3bb73b82aadf9b3672867297c812b28a1/src/PetriEngine/PQL/QueryPrinter.cpp#L146C25-L146C25
I would be grateful if you would let me know if this is the intended form.

Kind regards

**Comment by petergjoel** [comment]
That indeed looks like an issue. 
You are welcome to submit a PR with the fix if you want to be immortalized in the verifypn source-tree!
If not, I will submit one in the beginning of next week (probably).

**Comment by srba** [comment]
Thanks a lot for reporting the issue. I created the PR directly through the GUI.
