### ISSUE TITLE
LessThan for Color comparison leads to inf loop

### ISSUE THREAD

**Issue by petergjoel** [TAPAAL/verifypn#78]
for an color int range of `[2,3]` with a variable `v`of rthat type, doing a comparison `v<2` leads to an infinite loop in the unfolder.

**Comment by srba** [comment]
I can reproduce this problem with the following net that does not unfold
![Screenshot 2022-03-17 at 11 11 09](https://user-images.githubusercontent.com/7521926/158786919-d756beae-1304-4034-bb70-3d38e91fe192.png)
.
